# Generated by Django 4.1.1 on 2022-10-02 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=2000, null=True)),
                ('phone_no', models.CharField(max_length=2000, null=True)),
                ('message', models.TextField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('location', models.CharField(max_length=2000, null=True)),
                ('slug', models.SlugField(max_length=1000, null=True)),
                ('photo', models.ImageField(null=True, upload_to='featured_image/')),
                ('service_1', models.CharField(blank=True, max_length=200, null=True)),
                ('price_1', models.IntegerField(blank=True, null=True)),
                ('service_2', models.CharField(blank=True, max_length=200, null=True)),
                ('price_2', models.IntegerField(blank=True, null=True)),
                ('service_3', models.CharField(blank=True, max_length=200, null=True)),
                ('price_3', models.IntegerField(blank=True, null=True)),
                ('service_4', models.CharField(blank=True, max_length=200, null=True)),
                ('price_4', models.IntegerField(blank=True, null=True)),
                ('service_5', models.CharField(blank=True, max_length=200, null=True)),
                ('price_5', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.category')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('services_required', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
