# Generated by Django 4.1.1 on 2022-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_services_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
