# Generated by Django 4.1.1 on 2022-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_book_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ManyToManyField(to='booking.location'),
        ),
    ]
