# Generated by Django 4.1.1 on 2022-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_book_location_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
