# Generated by Django 4.1.1 on 2022-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_userprofile_alter_contact_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
