# Generated by Django 4.1.1 on 2022-10-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_userprofile_name_alter_userprofile_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='RegistrationForm',
        ),
    ]
