# Generated by Django 3.2.15 on 2022-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_registrationform_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
