# Generated by Django 3.2.15 on 2022-10-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
