# Generated by Django 3.2.15 on 2022-10-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
